[package]
name = "todolist"
version = "0.3.1"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
cursive = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
