[package]
name = "todod"
version = "0.1.3"
edition = "2021"

[dependencies]
inotify = "0.11.0"
chrono = "0.4.38"
eframe = { version = "0.28.1", features = ["default",] }
clap = { version = "4.5.18", features = ["derive"] }
